export const reassuranceMore: string[] = [
  "Short active periods are part of many flights.",
  "The route can adjust while the journey remains steady.",
  "The final part often feels more active than the middle.",
  "The beginning can feel stronger than the rest of the flight.",
  "You do not have to understand every sound.",
  "The app will keep the explanation simple.",
  "The journey is still moving forward.",
  "This sensation is common for passengers.",
  "It is okay if this feels uncomfortable.",
  "The flight can continue normally through this.",
  "This is one moment in a routine journey.",
  "The aircraft is not asking anything from you.",
  "You can let this moment pass.",
  "The current movement is part of the flight experience.",
  "The current sound is part of the flight experience.",
  "The cabin is being prepared in the usual way.",
  "Arrival can bring more noticeable changes.",
  "Cruise can feel quiet for a long time.",
  "Extra time can happen during normal travel.",
  "The flight is still within a calm flow.",
  "The next step will happen when the journey is ready.",
  "This is a normal moment to notice more details.",
  "You are being carried through a planned journey.",
  "This view is here to reduce uncertainty.",
  "The journey can continue calmly from here."
];
