export const reassuranceCore: string[] = [
  "Nothing unusual is happening right now.",
  "This is a routine part of the journey.",
  "The aircraft is continuing normally.",
  "You do not need to monitor every detail.",
  "The journey is moving steadily.",
  "This moment is expected during a normal flight.",
  "Most flights have moments like this.",
  "The flight is still following its planned rhythm.",
  "There is nothing you need to do right now.",
  "This can feel noticeable and still be normal.",
  "The current phase is part of ordinary flying.",
  "The aircraft is built for this part of the journey.",
  "The flight is progressing as expected.",
  "Small changes can happen during a normal flight.",
  "A change in sound does not mean something is wrong.",
  "A change in movement can be part of the route.",
  "The cabin may feel busier near key moments.",
  "The journey is continuing calmly.",
  "This is not something you need to solve.",
  "The flight crew sees moments like this often.",
  "Your only job is to stay seated and let the journey continue.",
  "The aircraft is still doing what it is designed to do.",
  "This part can feel different without being unusual.",
  "The next moment will become clearer as the journey continues.",
  "Long quiet periods are normal during flight."
];
